# Generated by Django 4.2 on 2023-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="on_hold",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
