# Generated by Django 4.2 on 2023-04-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "borrower",
            "0002_borrower_remove_userprofile_user_delete_loanrequest_and_more",
        ),
        ("investor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("loan_period", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="active", max_length=255)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrower.borrower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=255)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investor.investor",
                    ),
                ),
                (
                    "loan_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan.loanrequest",
                    ),
                ),
            ],
        ),
    ]
