# Generated by Django 4.2 on 2023-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanoffer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="loanoffer",
            name="interest_rate",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
