# Generated by Django 4.2 on 2023-04-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "borrower",
            "0002_borrower_remove_userprofile_user_delete_loanrequest_and_more",
        ),
        ("investor", "0002_investor_on_hold"),
        ("loan", "0002_loanoffer_updated_at_alter_loanoffer_interest_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("end_date", models.DateField()),
                (
                    "initial_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("duration", models.PositiveIntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("funded", "Funded"),
                            ("completed", "Completed"),
                            ("late", "Late"),
                        ],
                        default="funded",
                        max_length=20,
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="borrower.borrower",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investor.investor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("late", "Late"),
                            ("missed", "Missed"),
                        ],
                        default="due",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loan.loan"
                    ),
                ),
            ],
        ),
    ]
